#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=dropad

mkdir -p ../../../vendor/samsung/$DEVICE/proprietary
#
# Pull files here


(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/samsung/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/__DEVICE__/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    vendor/samsung/__DEVICE__/proprietary/libmoto_gps.so:obj/lib/libmoto_gps.so \\
    vendor/samsung/__DEVICE__/proprietary/libcamera.so:obj/lib/libcamera.so \\
    vendor/samsung/__DEVICE__/proprietary/libaudio.so:obj/lib/libaudio.so \\
    vendor/samsung/__DEVICE__/proprietary/libril_rds.so:obj/lib/libril_rds.so \\
    vendor/samsung/__DEVICE__/proprietary/libnmea.so:obj/lib/libnmea.so \\
    vendor/samsung/__DEVICE__/proprietary/gralloc.omap3.so:obj/lib/hw/gralloc.omap3.so \\

PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/ProgramMenuSystem.apk:/system/app/ProgramMenuSystem.apk \\
    vendor/samsung/__DEVICE__/proprietary/ProgramMenu.apk:/system/app/ProgramMenu.apk \\
    vendor/samsung/__DEVICE__/proprietary/PhoneConfig.apk:/system/app/PhoneConfig.apk

# All the blobs necessary for dropad
PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/libmoto_gps.so:/system/lib/libmoto_gps.so \\
    vendor/samsung/__DEVICE__/proprietary/libcamera.so:/system/lib/libcamera.so \\
    vendor/samsung/__DEVICE__/proprietary/libaudio.so:/system/lib/libaudio.so \\
    vendor/samsung/__DEVICE__/proprietary/libril_rds.so:/system/lib/libril_rds.so \\
    vendor/samsung/__DEVICE__/proprietary/libnmea.so:/system/lib/libnmea.so \\
    vendor/samsung/__DEVICE__/proprietary/libEGL_POWERVR_SGX530_121.so:/system/lib/egl/libEGL_POWERVR_SGX530_121.so \\
    vendor/samsung/__DEVICE__/proprietary/libGLESv1_CM_POWERVR_SGX530_121.so:/system/lib/egl/libGLESv1_CM_POWERVR_SGX530_121.so \\
    vendor/samsung/__DEVICE__/proprietary/libGLESv2_POWERVR_SGX530_121.so:/system/lib/egl/libGLESv2_POWERVR_SGX530_121.so \\
    vendor/samsung/__DEVICE__/proprietary/gralloc.omap3.so:/system/lib/hw/gralloc.omap3.so \\
    vendor/samsung/__DEVICE__/proprietary/libbattd.so:/system/lib/libbattd.so \\
    vendor/samsung/__DEVICE__/proprietary/libglslcompiler.so:/system/lib/libglslcompiler.so \\
    vendor/samsung/__DEVICE__/proprietary/libHPImgApi.so:/system/lib/libHPImgApi.so \\
    vendor/samsung/__DEVICE__/proprietary/libIMGegl.so:/system/lib/libIMGegl.so \\
    vendor/samsung/__DEVICE__/proprietary/libinterstitial.so:/system/lib/libinterstitial.so \\
    vendor/samsung/__DEVICE__/proprietary/libLCML.so:/system/lib/libLCML.so \\
    vendor/samsung/__DEVICE__/proprietary/liblvmxipc.so:/system/lib/liblvmxipc.so \\
    vendor/samsung/__DEVICE__/proprietary/libmoto_ril.so:/system/lib/libmoto_ril.so \\
    vendor/samsung/__DEVICE__/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \\
    vendor/samsung/__DEVICE__/proprietary/libOMX.TI.AAC.decode.so:/system/lib/libOMX.TI.AAC.decode.so \\
    vendor/samsung/__DEVICE__/proprietary/libOMX.TI.AMR.encode.so:/system/lib/libOMX.TI.AMR.encode.so \\
    vendor/samsung/__DEVICE__/proprietary/libOMX.TI.MP3.decode.so:/system/lib/libOMX.TI.MP3.decode.so \\
    vendor/samsung/__DEVICE__/proprietary/libOMX.TI.WBAMR.decode.so:/system/lib/libOMX.TI.WBAMR.decode.so \\
    vendor/samsung/__DEVICE__/proprietary/libOMX.TI.WMA.decode.so:/system/lib/libOMX.TI.WMA.decode.so \\
    vendor/samsung/__DEVICE__/proprietary/libopencore_asflocal.so:/system/lib/libopencore_asflocal.so \\
    vendor/samsung/__DEVICE__/proprietary/libopencore_asflocalreg.so:/system/lib/libopencore_asflocalreg.so \\
    vendor/samsung/__DEVICE__/proprietary/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \\
    vendor/samsung/__DEVICE__/proprietary/libpvr2d.so:/system/lib/libpvr2d.so \\
    vendor/samsung/__DEVICE__/proprietary/libpvrANDROID_WSEGL.so:/system/lib/libpvrANDROID_WSEGL.so \\
    vendor/samsung/__DEVICE__/proprietary/libspeech.so:/system/lib/libspeech.so \\
    vendor/samsung/__DEVICE__/proprietary/libsrv_um.so:/system/lib/libsrv_um.so \\
    vendor/samsung/__DEVICE__/proprietary/libVendor_ti_omx.so:/system/lib/libVendor_ti_omx.so \\
    vendor/samsung/__DEVICE__/proprietary/libVendor_ti_omx_config_parser.so:/system/lib/libVendor_ti_omx_config_parser.so \\
    vendor/samsung/__DEVICE__/proprietary/libzxing.so:/system/lib/libzxing.so \\
    vendor/samsung/__DEVICE__/proprietary/zxing.so:/system/lib/zxing.so \\
    vendor/samsung/__DEVICE__/proprietary/akmd2:/system/bin/akmd2 \\
    vendor/samsung/__DEVICE__/proprietary/ap_gain.bin:/system/bin/ap_gain.bin \\
    vendor/samsung/__DEVICE__/proprietary/battd:/system/bin/battd \\
    vendor/samsung/__DEVICE__/proprietary/bthelp:/system/bin/bthelp \\
    vendor/samsung/__DEVICE__/proprietary/chat-ril:/system/bin/chat-ril \\
    vendor/samsung/__DEVICE__/proprietary/ftmipcd:/system/bin/ftmipcd \\
    vendor/samsung/__DEVICE__/proprietary/mdm_panicd:/system/bin/mdm_panicd \\
    vendor/samsung/__DEVICE__/proprietary/pppd-ril:/system/bin/pppd-ril \\
    vendor/samsung/__DEVICE__/proprietary/pvrsrvinit:/system/bin/pvrsrvinit \\
    vendor/samsung/__DEVICE__/proprietary/SaveBPVer:/system/bin/SaveBPVer \\
    vendor/samsung/__DEVICE__/proprietary/tcmd:/system/bin/tcmd \\
    vendor/samsung/__DEVICE__/proprietary/01_Vendor_ti_omx.cfg:/system/etc/01_Vendor_ti_omx.cfg \\
    vendor/samsung/__DEVICE__/proprietary/cameraCalFileDef.bin:/system/etc/cameraCalFileDef.bin \\
    vendor/samsung/__DEVICE__/proprietary/contributors.css:/system/etc/contributors.css \\
    vendor/samsung/__DEVICE__/proprietary/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \\
    vendor/samsung/__DEVICE__/proprietary/wl1271.bin:/system/etc/firmware/wl1271.bin \\
    vendor/samsung/__DEVICE__/proprietary/gps.conf:/system/etc/gps.conf \\
    vendor/samsung/__DEVICE__/proprietary/key_code_map.txt:/system/etc/motorola/12m/key_code_map.txt \\
    vendor/samsung/__DEVICE__/proprietary/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \\
    vendor/samsung/__DEVICE__/proprietary/pvplayer_mot.cfg:/system/etc/pvplayer_mot.cfg \\
    vendor/samsung/__DEVICE__/proprietary/google_generic_update.txt:/system/etc/updatecmds/google_generic_update.txt \\
    vendor/samsung/__DEVICE__/proprietary/fw_wlan1271.bin:/system/etc/wifi/fw_wlan1271.bin \\
    vendor/samsung/__DEVICE__/proprietary/baseimage.dof:/system/lib/dsp/baseimage.dof \\
    vendor/samsung/__DEVICE__/proprietary/conversions.dll64P:/system/lib/dsp/conversions.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/h264vdec_sn.dll64P:/system/lib/dsp/h264vdec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/h264venc_sn.dll64P:/system/lib/dsp/h264venc_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/jpegenc_sn.dll64P:/system/lib/dsp/jpegenc_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/m4venc_sn.dll64P:/system/lib/dsp/m4venc_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/mp3dec_sn.dll64P:/system/lib/dsp/mp3dec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/mp4vdec_sn.dll64P:/system/lib/dsp/mp4vdec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/mpeg4aacdec_sn.dll64P:/system/lib/dsp/mpeg4aacdec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/mpeg4aacenc_sn.dll64P:/system/lib/dsp/mpeg4aacenc_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/nbamrdec_sn.dll64P:/system/lib/dsp/nbamrdec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/nbamrenc_sn.dll64P:/system/lib/dsp/nbamrenc_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/postprocessor_dualout.dll64P:/system/lib/dsp/postprocessor_dualout.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/ringio.dll64P:/system/lib/dsp/ringio.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/usn.dll64P:/system/lib/dsp/usn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/wbamrdec_sn.dll64P:/system/lib/dsp/wbamrdec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/wbamrenc_sn.dll64P:/system/lib/dsp/wbamrenc_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/wmadec_sn.dll64P:/system/lib/dsp/wmadec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/wmv9dec_sn.dll64P:/system/lib/dsp/wmv9dec_sn.dll64P \\
    vendor/samsung/__DEVICE__/proprietary/samsung-keypad.kcm.bin:/system/usr/keychars/dropad-keypad.kcm.bin \\
    vendor/samsung/__DEVICE__/proprietary/cpcap-key.kl:/system/usr/keylayout/cpcap-key.kl \\
    vendor/samsung/__DEVICE__/proprietary/dropad-keypad.kl:/system/usr/keylayout/dropad-keypad.kl


EOF

./setup-makefiles.sh
